name: Test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-1
    steps:
      - name: Run Ansible Playbook
        run: ansible-playbook -i ./hosts **.yml
